services:
  spark-master:
    container_name: da-spark-master
    build: .
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'

  spark-history-server:
    container_name: da-spark-history
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      spark-master:
        condition: service_healthy
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'

  spark-worker:
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      spark-master:
        condition: service_healthy
    env_file:
      - .env.spark
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events

  jupyter:
    container_name: da-spark-jupyter
    hostname: jupyter
    image: da-spark-image
    entrypoint: ['/opt/spark/entrypoint.sh', 'jupyter']
    depends_on:
      spark-master:
        condition: service_healthy
    env_file:
      - .env.spark
    environment:
      SPARK_DRIVER_HOST: jupyter
    volumes:
      - ./notebooks:/opt/spark/notebooks
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    ports:
      - '8888:8888'
      - '4040:4040'
    working_dir: /opt/spark/notebooks

volumes:
  spark-logs:
